# Generated by Django 3.2.5 on 2021-08-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
