# Generated by Django 3.2.5 on 2021-08-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0004_auto_20210811_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='notes',
            field=models.TextField(default=' '),
        ),
    ]
