# Generated by Django 3.2.5 on 2021-08-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0005_alter_author_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='books', to='books_authors_app.Book'),
        ),
    ]
